name: rivora
description: Rivora - Interactive Virtual Musical Instruments

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/branding/
    - assets/splash/
    - assets/images/drum_kit/
    - assets/sounds/drum_kit/
    - assets/sounds/xylophone/

